name: whatismyip
description: A lightweight Dart package that helps you discover your IP address and retrieve detailed geolocation information. This package integrates with Ipify for IP address lookup and IP2Location for geolocation data.
version: 1.0.0
homepage: https://github.com/anoochit/whatismyip

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  http: ^1.3.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
